<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="DNICSS.css" type="text/css"?>
<!DOCTYPE DNI [
    <!ELEMENT DNI (Foto, Nombre, Apellidos, Lugardenac, Provincia,
    Pais, Numero, FECHACAD, Progenitores)>
    <!ELEMENT Foto (#PCDATA)>
    <!ELEMENT Nombre (#PCDATA)>
    <!ELEMENT Apellidos (#PCDATA)>
    <!ELEMENT Lugardenac (#PCDATA)>
    <!ELEMENT Provincia (#PCDATA)>
    <!ELEMENT Pais (#PCDATA)>
    <!ELEMENT Numero (#PCDATA)>
    <!ELEMENT FECHACAD (#PCDATA)>
    <!ELEMENT Progenitores (NOMBRE, Apellido)*>
    <!ELEMENT NOMBRE (#PCDATA)>
    <!ELEMENT Apellido (#PCDATA)>
]>
<DNI>
    <Foto>Imagen</Foto>
    <Nombre>Roberto</Nombre>
    <Apellidos>Caballero López</Apellidos>
    <Lugardenac>Calzada de calatrava</Lugardenac>
    <Provincia>Ciudad Real</Provincia>
    <Pais>España</Pais>
    <Numero>059635151K</Numero>
    <FECHACAD>25/12/2025</FECHACAD>
    <Progenitores>
        <NOMBRE>Jose Ángel</NOMBRE>
        <Apellido>Pedro Bustos</Apellido>
        <NOMBRE>Josefa</NOMBRE>
        <Apellido>Romana Sanchez</Apellido>
    </Progenitores>
</DNI>